service: Empleados
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DYNAMODB_EMPLEADOS_TABLE: t-empleados-dev
    
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
            - 'dynamodb:Query'
          Resource: arn:aws:dynamodb:us-east-1:826921230004:table/t-empleados-dev
          #Resource: arn:aws:dynamodb:us-east-1:826921230004:table/ThomK-customerTable-dev


package: 
  individually: true
  patterns:
    - "!.dynamodb"
    - "!.node_modules"

custom:
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true


plugins:
  - serverless-offline
  - serverless-dynamodb-local


functions:
  create-empleados:
    handler: createempleados.createEmpleados
    events:
      - http:
          path: empleados
          method: post
          cors: true

  get-empleados:
    handler: getempleados.getEmpleados
    events: 
      - http:
          path: empleados/{id}
          method: get
          cors: true
          

  get-all-empleados:
    handler: getallempleados.getAllEmpleados
    events: 
      - http:
          path: empleados/all
          method: get
          cors: true
          
         

  update-empleados:
    handler: updateempleados.updateEmpleados
    events: 
      - http:
          path: empleados/{id}
          method: patch
          cors: true

  delete-empleados:
    handler: deleteempleados.deleteEmpleados
    runtime: python3.9
    events: 
      - http:
          path: empleados/{id}
          method: delete
          cors: true

  welcome:
    handler: index.handler
    events: 
      - http:
          path: /hello
          method: get
          cors: true

resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        TableName: t-empleados-dev